### ISSUE TITLE
Filter form not showing initial values when passed as form.inital

### ISSUE THREAD

**Issue by oaaoaa** [RamezIssac/django-slick-reporting#87]
I am trying to pass the start_date and end_date through a dictionary passed as form.initial in my customized SlickReportForm subclass in its __init__. The form gets created just fine but when I display the form through the standard templates in slick_reporting the start_date and end_date boxes show as empty. However when I set these through field.initial it works fine. My understanding is that form.initial should have an over ridding effect over field.initial, so why does this work with field.initial and not form.initial?

**Comment by RamezIssac** [comment]
Fixed on the develop branch;
Will release within the week.

**Comment by RamezIssac** [comment]
Hello ! This has been addressed and a new release is ready .

https://github.com/RamezIssac/django-slick-reporting/releases/tag/v1.2
