### ISSUE TITLE
ReportViewBase.get_context_data() creates a form without kwargs

### ISSUE THREAD

**Issue by oaaoaa** [RamezIssac/django-slick-reporting#89]
In get_context_data the form is created via get_form_class()() i.e. without any form parameters. Whereas in get method it is created via get_form(get_form_class()), i.e with form kwargs. There ought to be consistency as there might be important arguments to be passed to the form. Is there a reason why two different ways of creating the form have been used? I suspect that it is related to https://github.com/ra-systems/django-slick-reporting/issues/87

**Comment by RamezIssac** [comment]
Hello @oaaoaa 

This has been addressed and a new release is ready now 
https://github.com/RamezIssac/django-slick-reporting/releases/tag/v1.2
