### ISSUE TITLE
Question: ComputationField: want datetime difference

### ISSUE THREAD

**Issue by gillesserco** [RamezIssac/django-slick-reporting#97]
Hello

I would like to make a report (time series report?) showing average delay (stop - start datetime) per item_type between two dates, grouped by week.
All the info is present in the model, like start, stop, item_type.

I already have a report showing total of items (per type) over time and was hoping to use a custom ComputationField (or the used computation method), but I get nowhere.

Any example much appreciated...

best regards

gilles

PS:
I added a property in the model, and it is usefull when displaying a table, but it is not taken in consideration by slick reportin and result in ' Cannot resolve keyword 'availability_delay' into field' error

My model is like:
"""
class Product(models.Model):
    zone = models.CharField(max_length=40, blank=False, null=False)
    creation_date = models.DateTimeField(blank=True, null=True)
	discovered_at = models.DateTimeField(blank=True, null=True, default=datetime.now)

    class Meta:
        app_label = 'mod_asp'
        managed = True
        db_table = 'product'
		
    @property
    def availability_delay(self):
        return self.discovered_at - self.creation_date

"""

**Comment by RamezIssac** [comment]
Hello 
Slick reporting uses database fields to compute the results, _and not model properties._

For this case, you would need to either
1.  create a "materialized" column containing the date/time difference you want in the database table, and use it in the reports, 
OR
2. create a custom computation fiield as in https://django-slick-reporting.readthedocs.io/en/latest/topics/computation_field.html

Hope this helps and i apologize for the late reply 

Regards
